name: nested_navigation_gorouter_example
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  beamer: ^1.7.0
  auto_route: ^10.1.2
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  go_router: 16.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
